jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: Set version
      run: ./mvnw versions:set -DnewVersion="${{github.event.release.tag_name}}"
    - continue-on-error: true
      env:
        MAVEN_DEPLOYMENT_REPOSITORY: ${{ secrets.MAVEN_DEPLOYMENT_REPOSITORY }}
      name: Deploy with Maven
      run: ./mvnw deploy -DaltReleaseDeploymentRepository="$MAVEN_DEPLOYMENT_REPOSITORY"
        -DskipTests
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
